### PR TITLE
Powercord compatibility fix

### PR DESCRIPTION
**Pull request by lmarianski**
This makes the package compatible with Discord mods such as Powercord, BetterDiscord, etc.

(Although i only tested it with Powercord)

### CODE REVIEW

**Review by PedroHLC — APPROVED** [review]
Haven't tested it, but it's just a popd, and looks good to me!

**Comment by PedroHLC** [comment]
It packed right, but when I replaced my discord-canary-electron-bin with this one, it didn't work:
```
╰─λ discord-canary
Error launching app
Unable to find Electron app at /usr/lib/discord-canary/resources/app

Cannot find module '/usr/lib/discord-canary/resources/app'
Require stack:
- /usr/lib/electron/resources/default_app.asar/main.js
-
```

**Comment by Kodehawa** [comment]
Yeah, didn't work for me either. Will merge once it works!

Exams are killing me, send help :)

**Comment by lmarianski** [comment]
Hmm, interesting
Ahhh, i think i know why
i guess i forgot to test the package *without* Powercord
lemme see what i can do about it

**Comment by lmarianski** [comment]
This feels a bit hacky, but it works both /w Powercord and /wo

**Comment by Kodehawa** [comment]
Wouldn't that open any app that starts with "app" on that folder? Little cursed 🤔

**Comment by Kodehawa** [comment]
@PedroHLC what do ya say?

**Comment by PedroHLC** [comment]
> Wouldn't that open any app that starts with "app" on that folder? Little cursed thinking.

Yeah, I was thinking about making it either dynamic:
```
echo "[ -f /usr/lib/$_pkgname/resources/app/powercord ] && exec /usr/lib/$_pkgname/resources/app/powercord"
```

Or, as CLI parameter: `discord-canary --app=powercord`.

This second one could allow powercord to be installed as a secondary package and started using a secondary desktop unit.

**Comment by PedroHLC** [comment]
@lmarianski do you think you can do it?

**Comment by lmarianski** [comment]
Well, that isn't how powercord works, it puts its files in a `app` folder in the same dir as the `app.asar`.
@Kodehawa electron only executes the first thing passed to it as an argument
hmm, idk

**Comment by lmarianski** [comment]
This is the dir structure /w Powercord installed:
```
.
├── app
│   ├── index.js
│   └── package.json
├── app.asar
├── bootstrap
│   └── manifest.json
└── build_info.json
```

**Comment by lmarianski** [comment]
But maybe i could go and do a patch/PR to powercord + an AUR package to make this a bit easier

**Comment by Kodehawa** [comment]
> But maybe i could go and make a patch/PR to powercord + an AUR package to make this a bit easier
> 
> (altho then the other discord canary package would need changes too for compatibility)

What are you gonna do?

**Comment by lmarianski** [comment]
I think i figured out the best way to do this, i'm making a powercord AUR package which will have a separate script to launch discord+powercord, then here i'll revert the `*` change.

**Comment by lmarianski** [comment]
(although to be fair, this does make the PR unnecessary, since in my package i can just use the path that this package installs discord at)

**Comment by lmarianski** [comment]
This does make the PR unnecesary, though

**Comment by lmarianski** [comment]
Here's the aur package: https://aur.archlinux.org/packages/powercord-electron-git/

**Pull request closed without merging**
